GET http://localhost:8000/api
Content-Type: application/json

###

GET http://localhost:8000/api/health
Content-Type: application/json

###

GET http://localhost:8000/api/prospect?nome_da_empresa=Google&website=https://google.com
Content-Type: application/json